---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-app-1
  name: backend-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app-1
  template:
    metadata:
      labels:
        app: backend-app-1
    spec:
      containers:
      - name: backend-app-1
        image: nginx:1.21.6-alpine
      restartPolicy: Always