---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-app-2
  name: backend-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app-2
  template:
    metadata:
      labels:
        app: backend-app-2
    spec:
      containers:
      - name: backend-app-2
        image: nginx:1.21.6-alpine
      restartPolicy: Always